drop table friends;
drop table business_hour;
drop table business_attribute;
drop table business_main_category;
drop table business_sub_category;
drop table business_checkin;
drop table yelp_review;
drop table yelp_user;
drop table business;